export const UPDATE_QUERY = 'UPDATE_QUERY'
export const ADD_PERSON = 'ADD_PERSON'
export const UPDATE_PERSON = 'UPDATE_PERSON'
export const DELETE_PERSON = 'DELETE_PERSON'
export const ADD_TOAST = 'ADD_TOAST'
export const CLOSE_TOAST = 'CLOSE_TOAST'
